### ISSUE TITLE
rofi ??

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#10]
needs to be added to the list of applications

+5)-add rofi? will need to add keybind to conky

not sure what this is at the moment

**Comment by Dobbie03** [comment]
+5) = make this an addition for the +5 release

Also so people are aware of the fact that rofi exists in AL, add the keybind/short cut to the list in the default conky.

Not required to be looked at until +5

**Comment by osgyan** [comment]
dont't add stuff. We want whatever is in BL, if rofi is there add it if not don't add, User can install this from AUR if required.
