### ISSUE TITLE
obmenu3

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#102]
Check if obmenu3 is better, stable etc...
[forum](http://archlabs.prophpbb.com/post702.html#p702)

**Comment by toola69** [comment]
@erikdubois I installed it but I couldn't get it to work

**Comment by erikdubois** [comment]
if you cannot - our users cannot

**Comment by erikdubois** [comment]
obmenu3 looks to be superior imo

**Comment by erikdubois** [comment]
is installed after testing and replaces obmenu
