### ISSUE TITLE
Removal of Pamac

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso#103]
See comment from Head_on_a_Stick (a Arch and Debian guru) regarding Pamac:

https://forums.bunsenlabs.org/viewtopic.php?pid=50239#p50239

I was actually unaware of this issue.  My suggestion is do do away with any type of GUI updater and use pacli in place of

@erikdubois @toola69

**Comment by erikdubois** [comment]
as it seems there is no issue at all... question has been put at github of pamac.
with a satisfying answer as a result. [link](https://github.com/manjaro/pamac/issues/248)

**Comment by Dobbie03** [comment]
Closing.

**Comment by AladW** [comment]
https://github.com/manjaro/pamac/issues/248#issuecomment-318051025

**Comment by Dobbie03** [comment]
Reopening issue until there is a satisfactory reply from Manjaro.

**Comment by Dobbie03** [comment]
Removed in favour of Pacli.
