### ISSUE TITLE
Inconsistent icons in obmenu-generator

### ISSUE THREAD

**Issue by toola69** [ARCHLabs/Archlabs-Iso#104]
@erikdubois @Dobbie03 Got a great review from Sudo Reboot on youtube.
He is having problems with missing icons when generating a menu with icons using 
obmenu-generator. He has tried different icon themes but still missing icons.
He said it was fine in the release before 4.
Has obmenu-generator been updated? If so can we rollback to the version before.

**Comment by Dobbie03** [comment]
Do we really require this?

**Comment by erikdubois** [comment]
it is a nice to have - will check it

**Comment by erikdubois** [comment]
at the moment obmenu-generator is giving issues with icons
lets wait until everything stabilizes

**Comment by erikdubois** [comment]
all icons have been accounted for
IF you use sardi or surfn all should be good
those icons sets can be controlled by archlabs team (me) and rest is third party like papirus, numix, etc...
