### ISSUE TITLE
audacious

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#107]
audacious is still being installed and is in rc.xml as shortcut super+m?

Deadbeef replaced musicplayer
Trimming iso and getting rid of audacious?
Ok to proceed

and changing super+m to start deadbeef

**Comment by Dobbie03** [comment]
Remove Audacious.  From a personal stand point, I will always change it back as I have had zero issues with Audacious.

**Comment by darknetmatrix** [comment]
remove audacious imo but also have a look at Pragha music player

**Comment by Dobbie03** [comment]
We don't want to over complicate things, thanks for the idea. Deadbeef is the default for now.

**Comment by erikdubois** [comment]
@darknetmatrix i have a script on [github](https://github.com/erikdubois/Archlabs-Nemesis/tree/master/Scripts%20to%20change%20openbox)
it is a script to change whatever application or keyboard shortcut there is to something you would want to use

**Comment by erikdubois** [comment]
audacious is going out - deadbeef is the music player for now
personally i will be using spotify
it is up to the end-user to change things like that
