### ISSUE TITLE
Papirus icon set

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#11]
needs to be added to the application list

**Comment by osgyan** [comment]
In 3.3.1 and in archlabs_repo sync and install it now

**Comment by erikdubois** [comment]
Papirus icon is not installed in ARCHLabs 3.2.1
Normal ?

**Comment by Dobbie03** [comment]
Not installed, needs to be added to next release.

**Comment by osgyan** [comment]
It is in the archlabs_repos. Install it with sudo pacman -S papirus-icons
