### ISSUE TITLE
Obladi

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#114]
instead of obmenu and obmenu3 we can use this one
[forum](http://archlabs.prophpbb.com/post1149.html#p1149)

**Comment by Dobbie03** [comment]
I still don't agree with the inclusion of a GUI for editing obmenu.  You can still cock-up your setup if you don't know what you are doing with the GUI and if you don't know how to repair the menu.xml in a text editor file you are totally stuffed.

I understand we are trying to make AL as user friendly as possible but some times the user has to get their hands dirty in the terminal and text editors.  Windows users sometimes need to access and edit the registry and AL is no different.

**_If_** we are going to include this I believe we need a tutorial on how to fix your menu.xml if you make an error in the GUI.

**Comment by erikdubois** [comment]
and how can you make an error?
what kind of tutorial do you require?

**Comment by Dobbie03** [comment]
Quite easily, a typo, the wrong entry for the wrong application.  Many ways to cock up using the GUI.

Actually I'd rather not see any GUI included.

**Comment by erikdubois** [comment]
let us keep this one in mind for an alternative for obmenu3
made quite a few changes with obmenu3 
all works fine
