### ISSUE TITLE
dropbox-plugin

### ISSUE THREAD

**Issue by darknetmatrix** [ARCHLabs/Archlabs-Iso#117]
maybe for future releases include the thunar-dropbox plugin, the size of it is 16.4 kb

**Comment by erikdubois** [comment]
do you use it? I do not 
what does it do?

**Comment by darknetmatrix** [comment]
It shows your dropbox map in thunar

**Comment by erikdubois** [comment]
in the right mouse click menu?

**Comment by darknetmatrix** [comment]
no, it creates a map in thunar just like musi, pictures, videos, ...

**Comment by erikdubois** [comment]
installed will follow it up
packer thunar-dropbox
that one right?

**Comment by darknetmatrix** [comment]
yes Erik

**Comment by erikdubois** [comment]
if we include that we need to include dropbox as well...
all cloud applications have not been included
as not everyone will like them or have them
I would like to have insync
but it is not in there.
Let me discuss it with the others.
