### ISSUE TITLE
Error while installing archlabs in virtualbox

### ISSUE THREAD

**Issue by shibasisp** [ARCHLabs/Archlabs-Iso#119]
While installing `archlabs-v4.1.0-2017.06.04` into VirtualBox, I get the following error:
![screenshot from 2017-06-19 13-37-50](https://user-images.githubusercontent.com/13582547/27278958-9cadc660-5500-11e7-8042-1c91f08cb230.jpg)
How can I resolve this?

**Comment by erikdubois** [comment]
this should not happen frankly

**Comment by erikdubois** [comment]
did you update in the live cd
then it makes sense again

**Comment by shibasisp** [comment]
No, I just downloaded the iso and installed it. I did nothing in between with live cd.

**Comment by erikdubois** [comment]
strange

**Comment by erikdubois** [comment]
try again with a new download please

**Comment by shibasisp** [comment]
Okay. Will try again with a fresh download.
Thanks!

**Comment by erikdubois** [comment]
good luck

**Comment by erikdubois** [comment]
can I close this one?

**Comment by shibasisp** [comment]
Okay

On Jun 20, 2017 9:47 AM, "Erik Dubois" <notifications@github.com> wrote:

can I close this one?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/ARCHLabs/Archlabs-Iso/issues/119#issuecomment-309640383>,
or mute the thread

**Comment by erikdubois** [comment]
thanks
