### ISSUE TITLE
bug after clean install

### ISSUE THREAD

**Issue by joksik** [ARCHLabs/Archlabs-Iso#123]
hello i install latest archlabs iso 4.1 and  when i boot my computer i have  this error:

**Failed to start Load Kernel Modules**

sudo systemctl status systemd-modules-load.service

● ```
systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2017-06-24 12:31:58 CEST; 9min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 168 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 168 (code=exited, status=1/FAILURE)

cze 24 12:31:58 arch-pc systemd-modules-load[168]: Failed to insert 'vboxguest': No such device
cze 24 12:31:58 arch-pc systemd-modules-load[168]: Failed to insert 'vboxsf': No such device
cze 24 12:31:58 arch-pc systemd-modules-load[168]: Failed to insert 'vboxvideo': No such device
cze 24 12:31:58 arch-pc systemd-modules-load[168]: Failed to insert 'vboxguest': No such device
cze 24 12:31:58 arch-pc systemd-modules-load[168]: Failed to insert 'vboxsf': No such device
cze 24 12:31:58 arch-pc systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
cze 24 12:31:58 arch-pc systemd[1]: Failed to start Load Kernel Modules.
cze 24 12:31:58 arch-pc systemd[1]: systemd-modules-load.service: Unit entered failed state.
cze 24 12:31:58 arch-pc systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

```

archlabs so far works great! only this message at boot

**Comment by erikdubois** [comment]
known issues
not a bug
check forum for more info
http://archlabs.prophpbb.com/topic193.html
