### ISSUE TITLE
.bashrc & .zshrc inclusions?

### ISSUE THREAD

**Issue by natemaia** [ARCHLabs/Archlabs-Iso#124]
First off zsh

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt AUTO_CD                                        # No cd needed to change directories

Then bash

shopt -s autocd             # change to named directory
shopt -s cdspell            # autocorrects cd misspellings
shopt -s cmdhist            # save multi-line commands in history as single line
shopt -s histappend         # do not overwrite history
shopt -s expand_aliases     # expand aliases

**Comment by erikdubois** [comment]
not much documentation about this online?

**Comment by natemaia** [comment]
for bash https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html

and for zsh http://zsh.sourceforge.net/Doc/Release/Options.html

**Comment by erikdubois** [comment]
has been added
including comments behind it
