### ISSUE TITLE
Automatically create bookmarks in thunar for users

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#126]
We can use a script and the service to run to  make 
~/config/gtk-3.0/bookmarks and put in the following folders upon installation
file:///home/erik/Downloads Downloads
file:///home/erik/Documents Documents
file:///home/erik/Music Music
file:///home/erik/Pictures Pictures
file:///home/erik/Videos Videos
file:///home/erik/.config .config
file:///home/erik/.config/conky conky
file:///home/erik/.config/openbox openbox
file:///home/erik/.config/i3

https://arashmilani.com/post?id=86

**Comment by erikdubois** [comment]
we can run hardcodefixer as well then

**Comment by erikdubois** [comment]
we can install archlabs-slimlock-themes

**Comment by Dobbie03** [comment]
Implemented in Minimo
