### ISSUE TITLE
touchpad - double tap to hold and drag

### ISSUE THREAD

**Issue by chiru459** [ARCHLabs/Archlabs-Iso#128]

**Comment by erikdubois** [comment]
thanks

**Comment by erikdubois** [comment]
battery indicator will be there in R2-D2 - you will get a percentage not an icon

**Comment by prajapatiravi257** [comment]
Any workaround for the double tap to hold and drag issue?

**Comment by chiru459** [comment]
I'm sure there was a solution posted, do you want me to send the link?

**Comment by natemaia** [comment]
double tap to drag solution here
http://archlabs.prophpbb.com/topic279.html

**Comment by natemaia** [comment]
A user on G+ was wondering if it is possible to have dragging by double tapping the touchpad on the widow titlebar, in short yes.. A lot is possible on openbox, most of which is handled within  [quote]~/.config/openbox/rc.xml[/quote]
So, how do I get this to work?

First open your rc.xml located above. You will have to edit a portion of it containing mouse bindings.
In the Archlabs default it's the binding at lines 816-818 that needs changing
It must be within the TitleBar context section[code]<context name="TitleBar">
  
  
</context>[/code]

Replace
[code]      <mousebind action="DoubleClick" button="Left">
        <action name="ToggleMaximizeFull"/>
      </mousebind>[/code]

With this [code]      <mousebind action="DoubleClick" button="Left">
        <action name="Move"/>
      </mousebind>[/code]

If you prefer single click to activate (less recommended)
[code]      <mousebind action="Click" button="Left">
        <action name="Move"/>
      </mousebind>[/code]

If you want a faster or slower double tap time, you can edit 
[quote]/etc/X11/xorg.conf.d/70-synaptics.conf[/quote]
Adjust MaxTapTime (lower is faster | higher is slower)
[code]Section "InputClass"
    Identifier "touchpad"
    Driver "synaptics"
    MatchIsTouchpad "on"
        Option "TapButton1" "1"
        Option "TapButton2" "3"
        Option "TapButton3" "2"
        Option "VertEdgeScroll" "on"
        Option "HorizEdgeScroll" "on"
        Option "MaxTapTime" "125"[/code]
More information can be found here [url]https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Frequently_used_options[/url] & [url]http://openbox.org/wiki/Help:Bindings[/url]

Anyone else with useful bindings for [b][u]mouse and touchpad only[/u][/b] should post here for helping others

Hope this was helpful,
Smoke
