### ISSUE TITLE
Post install applications

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#130]
can we make something graphical to install extra and delete what we have already installed
This is a script - need it to be an application (ubuntu-tweak look)
https://github.com/snwh/ubuntu-post-install

**Comment by Dobbie03** [comment]
I think this is a good idea, a big step towards shrinking the ISO.

**Comment by erikdubois** [comment]
i do not want to shrink the iso
i want them to give an easy application to delete stuff or install stuff

**Comment by Dobbie03** [comment]
@natemaia 

Script implemented in Minimo.
