### ISSUE TITLE
Add xfce4-power-manager to tray in favor of tint2 battery

### ISSUE THREAD

**Issue by natemaia** [ARCHLabs/Archlabs-Iso#132]
We can enable the tray icon for xfce4-power-manager via 

/etc/skel/.config/xfce4/xfce-perchannel-xml/xfce4-power-manager.xml

and adding ```<property name="show-tray-icon" type="bool" value="true">```

We could also probably use laptop-detect & grep to do a sed true/false depending on whether it is a laptop or not

**Comment by Dobbie03** [comment]
Does this fit in nicely with icon themes?

**Comment by natemaia** [comment]
Yea it's just like networkmanager, most themes have an icon- a little battery in this case

**Comment by Dobbie03** [comment]
No need with Polybar :D
