### ISSUE TITLE
neofetch-git is behind neofetch in AUR

### ISSUE THREAD

**Issue by sqamsqam** [ARCHLabs/Archlabs-Iso#136]
Please update to using neofetch instead of neofetch-git to resolve this issue 

`
/usr/bin/neofetch: line 2472: width / font_width + gap + xoffset/font_width: division by 0 (error token is "font_width + gap + xoffset/font_width")
`
When replacing neofetch-git with neofetch the issue is resolved.

**Comment by natemaia** [comment]
Thanks for the heads up.. 
Totally unrelated but I just got finished doing all our packaging and neofetch was switched along with a few other packages, We no longer have the need to include packages from the aur and will be largely managing our own repo for the things we need that aren't a part of arch official repo's
[See]https://github.com/ARCHLabs/archlabs_repo

All our packages are now signed and we have an archlabs keyring

You can either import our keys then have the trustdb checks
`gpg --receive-keys C1A60EACE707FDA5
gpg --receive-keys AEFB411B072836CD48FF0381AE252C284B5DBA5D
gpg --receive-keys 9E4F11C6A072942A7B3FD3B0B81EB14A09A25EB0
gpg --receive-keys 35F52A02854DCCAEC9DD5CC410443C7F54B00041

pacman-key --init
pacman-key --populate archlinux

pacman-key -r AEFB411B072836CD48FF0381AE252C284B5DBA5D
pacman-key -r 9E4F11C6A072942A7B3FD3B0B81EB14A09A25EB0
pacman-key -r 35F52A02854DCCAEC9DD5CC410443C7F54B00041`

Add to /etc/pacman.conf
`[archlabs_repo]
Server = https://archlabs.github.io/archlabs_repo/$arch
Server = https://downloads.sourceforge.net/project/archlabs-repo/archlabs_repo/$arch`

After both of these you should install the keyrings and initialize it
`sudo pacman -S archlabs-keyring
sudo pacman-key --populate archlabs`

Update and install what you'd like or the whole 'archlabs' group, most packages have conflicts, depends and provides etc. sorted out but you may have a few 'file exists' errors, just remove the files in question


Hope this helps in the future
Nate
