### ISSUE TITLE
Fresh Install in Oracle VirtualBox kernel panics on boot

### ISSUE THREAD

**Issue by badmark** [ARCHLabs/Archlabs-Iso#137]
Made a clone of previous ArchLabs Minimo VM and installed the latest version (2017-10-lts). 

Install went without a hitch, upon reboot:

```
starting version 235
/init: source: line 18: openswap.conf: not found....
```

Primary partition is encrypted, that would be the only out of the ordinary option.

Screenshot attached:
![archlabs_vm](https://user-images.githubusercontent.com/7435884/32516366-1bd48778-c3d1-11e7-9872-270e272ea972.png)

**Comment by badmark** [comment]
Virtual Machine does not panic when drive is not encrypted, could there be an issue with the implementation on this version as I previously had no issue on the previous release (running bare metal on primary workstation)?

Though the kernel does not throw a panic, system stops at a black screen with blinking cursor. 



Again, installer works fine and shows no errors.

**Comment by badmark** [comment]
Xorg log file after first boot (no encryption)

`[    11.555] 
X.Org X Server 1.19.5
Release Date: 2017-10-12
[    11.555] X Protocol Version 11, Revision 0
[    11.555] Build Operating System: Linux 4.9.54-1-lts x86_64 
[    11.555] Current Operating System: Linux mark-pc 4.9.60-1-lts #1 SMP Thu Nov 2 16:48:25 CET 2017 x86_64
[    11.555] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-linux-lts root=UUID=467a0e68-3ffd-424d-9cd7-d23d2c97f17d rw quiet resume=UUID=3000d670-93bd-4a56-84be-801c3f82565b nowatchdog systemd.legacy_systemd_cgroup_controller=true nomodeset noacpi noapic
[    11.555] Build Date: 12 October 2017  09:59:53PM
[    11.555]  
[    11.555] Current version of pixman: 0.34.0
[    11.555] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    11.555] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    11.555] (==) Log file: "/var/log/Xorg.0.log", Time: Tue Nov  7 16:12:30 2017
[    11.555] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    11.555] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    11.555] (==) No Layout section.  Using the first Screen section.
[    11.555] (==) No screen section available. Using defaults.
[    11.555] (**) |-->Screen "Default Screen Section" (0)
[    11.555] (**) |   |-->Monitor "<default monitor>"
[    11.555] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    11.555] (**) Option "DontZap" "false"
[    11.555] (==) Automatically adding devices
[    11.555] (==) Automatically enabling devices
[    11.555] (==) Automatically adding GPU devices
[    11.555] (==) Automatically binding GPU devices
[    11.555] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    11.555] (WW) The directory "/usr/share/fonts/Type1/" does not exist.
[    11.555] 	Entry deleted from font path.
[    11.555] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/100dpi/".
[    11.555] 	Entry deleted from font path.
[    11.555] 	(Run 'mkfontdir' on "/usr/share/fonts/100dpi/").
[    11.555] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/75dpi/".
[    11.555] 	Entry deleted from font path.
[    11.555] 	(Run 'mkfontdir' on "/usr/share/fonts/75dpi/").
[    11.555] (==) FontPath set to:
	/usr/share/fonts/misc/,
	/usr/share/fonts/TTF/,
	/usr/share/fonts/OTF/
[    11.555] (==) ModulePath set to "/usr/lib/xorg/modules"
[    11.555] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    11.555] (II) Loader magic: 0x56445e9dad60
[    11.555] (II) Module ABI versions:
[    11.555] 	X.Org ANSI C Emulation: 0.4
[    11.555] 	X.Org Video Driver: 23.0
[    11.555] 	X.Org XInput driver : 24.1
[    11.555] 	X.Org Server Extension : 10.0
[    11.556] (++) using VT number 7

[    11.556] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    11.557] (--) PCI:*(0:0:2:0) 80ee:beef:0000:0000 rev 0, Mem @ 0xe0000000/134217728, BIOS @ 0x????????/131072
[    11.557] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[    11.557] (II) LoadModule: "glx"
[    11.558] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    11.558] (II) Module glx: vendor="X.Org Foundation"
[    11.558] 	compiled for 1.19.5, module version = 1.0.0
[    11.558] 	ABI class: X.Org Server Extension, version 10.0
[    11.558] (==) Matched vboxvideo as autoconfigured driver 0
[    11.558] (==) Matched modesetting as autoconfigured driver 1
[    11.558] (==) Matched fbdev as autoconfigured driver 2
[    11.558] (==) Matched vesa as autoconfigured driver 3
[    11.558] (==) Assigned the driver to the xf86ConfigLayout
[    11.558] (II) LoadModule: "vboxvideo"
[    11.558] (WW) Warning, couldn't open module vboxvideo
[    11.558] (II) UnloadModule: "vboxvideo"
[    11.558] (II) Unloading vboxvideo
[    11.558] (EE) Failed to load module "vboxvideo" (module does not exist, 0)
[    11.558] (II) LoadModule: "modesetting"
[    11.558] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[    11.559] (II) Module modesetting: vendor="X.Org Foundation"
[    11.559] 	compiled for 1.19.5, module version = 1.19.5
[    11.559] 	Module class: X.Org Video Driver
[    11.559] 	ABI class: X.Org Video Driver, version 23.0
[    11.559] (II) LoadModule: "fbdev"
[    11.559] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[    11.559] (II) Module fbdev: vendor="X.Org Foundation"
[    11.559] 	compiled for 1.19.3, module version = 0.4.4
[    11.559] 	Module class: X.Org Video Driver
[    11.559] 	ABI class: X.Org Video Driver, version 23.0
[    11.559] (II) LoadModule: "vesa"
[    11.559] (II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[    11.559] (II) Module vesa: vendor="X.Org Foundation"
[    11.559] 	compiled for 1.19.3, module version = 2.3.4
[    11.559] 	Module class: X.Org Video Driver
[    11.559] 	ABI class: X.Org Video Driver, version 23.0
[    11.559] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[    11.559] (II) FBDEV: driver for framebuffer: fbdev
[    11.559] (II) VESA: driver for VESA chipsets: vesa
[    11.559] (EE) open /dev/dri/card0: No such file or directory
[    11.559] (WW) Falling back to old probe method for modesetting
[    11.559] (EE) open /dev/dri/card0: No such file or directory
[    11.559] (II) Loading sub module "fbdevhw"
[    11.559] (II) LoadModule: "fbdevhw"
[    11.559] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    11.559] (II) Module fbdevhw: vendor="X.Org Foundation"
[    11.559] 	compiled for 1.19.5, module version = 0.0.2
[    11.559] 	ABI class: X.Org Video Driver, version 23.0
[    11.559] (EE) Unable to find a valid framebuffer device
[    11.559] (WW) Falling back to old probe method for fbdev
[    11.559] (II) Loading sub module "fbdevhw"
[    11.559] (II) LoadModule: "fbdevhw"
[    11.559] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    11.559] (II) Module fbdevhw: vendor="X.Org Foundation"
[    11.559] 	compiled for 1.19.5, module version = 0.0.2
[    11.559] 	ABI class: X.Org Video Driver, version 23.0
[    11.559] (II) FBDEV(2): using default device
[    11.559] (EE) Screen 0 deleted because of no matching config section.
[    11.559] (II) UnloadModule: "modesetting"
[    11.559] (EE) Screen 0 deleted because of no matching config section.
[    11.559] (II) UnloadModule: "fbdev"
[    11.559] (II) UnloadSubModule: "fbdevhw"
[    11.559] (EE) 
Fatal server error:
[    11.559] (EE) Cannot run in framebuffer mode. Please specify busIDs        for all framebuffer devices
[    11.559] (EE) 
[    11.559] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[    11.559] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    11.559] (EE) 
[    11.560] (EE) Server terminated with error (1). Closing log file.
`

**Comment by badmark** [comment]
![virtualbox_pc-alm-10_08_11_2017_07_42_42](https://user-images.githubusercontent.com/7435884/32549721-7f61aa46-c458-11e7-9c02-366139ee43fc.png)

Same with non-lts image on VirtualBox...

**Comment by Dobbie03** [comment]
Wow this is way beyond me, @natemaia , can you help here?

**Comment by natemaia** [comment]
New iso is on it's way out soon, hopefully you can give it a try..

If this is still an issue I can be more proactive with it once were past the release

Apologies for the delay

**Comment by badmark** [comment]
Awesome, will report back!
