### ISSUE TITLE
Error when installing new packages after using "13 Fix Errors" from pacli

### ISSUE THREAD

**Issue by MyIsaak** [ARCHLabs/Archlabs-Iso#138]
I get the error below every time I try to sync or install packages. This started after I tried to clean my system running the `13 Fix Errors` option from the package manager `pacli`. I am unable to install anything at all without this error.

```
error: archlabs_repo: signature from "Nathaniel Maia <natemaia10@gmail.com>" is unknown trust
error: database 'archlabs_repo' is not valid (invalid or corrupted database (PGP signature))
```

I got this output when running: 
`sudo gpg --list-keys --fingerprint natemaia10@gmail.com`                           
```
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: error reading key: No public key
```

**Comment by natemaia** [comment]
Why are you running gpg as root?

**Comment by Dobbie03** [comment]
I think we can close this one Smoke.
