### ISSUE TITLE
Installer abif on another Linux Distribution

### ISSUE THREAD

**Issue by kibojoe** [ARCHLabs/Archlabs-Iso#139]
hi all,
i'm Holmes and congratulations on your great work!
i am the maintainer of Kibojoe Linux (http://kibojoe.org/)
a Manjaro Linux re-spin with JWM
i'm interested in using your installer (abif)
my biggest goal with this is to reduce the size of the iso
with Calamares the iso becomes swollen
i have not studied the abif script yet, but the installation process seems very simple
i wonder if he has some dependency to run?

vlw fwi, Holmes :)

**Comment by natemaia** [comment]
Helllo Holmes, 
Thanks for the Interest

There is a few required packages for abif to work fully
- dialog  (* this one is really needed)
- wipe   (needed for secure wipe formatting option)
- os-prober  (needed for proper multiboot detection in grub)
- mkinitcpio-openswap   (needed for full drive encryption)

I'd be happy to answer any other quetions you have regarding the installer and it's inner workings
I'm not the original author, however I went through most of it and did a lot of cleaning up and tweaking for our situation

There is also more available options regarding package choosing, bootloader choices, addittional setup options.. We removed most of these from our version, in an attempt at making things easier / more streamlined

Let me know if you got any question

Cheers,
Nate

**Comment by Dobbie03** [comment]
This isn't an issue with ArchLabs so I'm going to close this one.  

@kibojoe, feel free to continue this conversation at the forum https://forum.archlabslinux.com/
