### ISSUE TITLE
-add GIMP and Libreoffice splash

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#14]
-add GIMP and Libreoffice splash

**Comment by osgyan** [comment]
Removed gimp from 3.2, it will be added again along with Splash Screen. Need to talk to Brett about how to get that moving

**Comment by erikdubois** [comment]
Why remove gimp.... ?
essential application

**Comment by Dobbie03** [comment]
@erikdubois seems to be a temporary removal, @osgyan will add it with the updated splash.

**Comment by osgyan** [comment]
Please add complete instructions for the configuration of these two Items and I will include this in next 3.4 build.

**Comment by osgyan** [comment]
Please update instructions. I will include in 3.4

**Comment by Dobbie03** [comment]
@toola69 can you add the new splash to the repo please.

**Comment by erikdubois** [comment]
what needs to be done here?

**Comment by toola69** [comment]
@erikdubois Matt has the splash mate and can tell you what to do.
@Dobbie03 Hey mate can you get the splash to Erik mate.

**Comment by Dobbie03** [comment]
Sorry guys, it was on my other drive which shat itself.  @toola69 do you still have a copy?

**Comment by toola69** [comment]
@Dobbie03 I'll scope it out mate

**Comment by erikdubois** [comment]
closing this one - do not see the sense in doing this... and then the maintenance with each new release...
