### ISSUE TITLE
Mirrorlist used in installer

### ISSUE THREAD

**Issue by slfmessi** [ARCHLabs/Archlabs-Iso#143]
Hi,
Thanks to your effort to make a wonderful distribution, I like this Archlabs though I have a little suggestion:

People in some regions (like me, in China) may download packages in slow speed during installing Archlabs,  because the mirrorlist doesn't fit them. How about let users choose their countries and generate mirrorlist by their countries?

**Comment by natemaia** [comment]
This should be resolved, the mirrorlist is automatically configured to use the top 20 mirrors with the best connection to you with `reflector` before any packages are installed or updated, if it is still an issue after next release we can look into adding an option to manually set it, however I wouldn't expect much difference.

Cheers
