### ISSUE TITLE
Recent update broke i3lock-fancy

### ISSUE THREAD

**Issue by rmbrntt** [ARCHLabs/Archlabs-Iso#144]
Had been using the 'lock'  option from oblogout menu and noticed it wasn't actually locking as of this past week? 

Running the cmd from oblogout to see what the result would be:
```
i3lock-fancy -p
convert: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/4162.
```

**Comment by Dobbie03** [comment]
Yup Nate and I are working on it.

**Comment by rmbrntt** [comment]
Latest release appears to have resolved this, closing this issue. Great job guys.

Do you happen to have the commit or PR so I can learn the magic behind this fix? I'd like to contribute in the future rather than just report. Appreciate it!

**Comment by natemaia** [comment]
@rmbrntt Sure thing, it was regarding font rendering and which library is used
Commit is here https://github.com/ARCHLabs/ArchLabs-screenlock/commit/bb1a7123bc58db5473bd92131b2b4dc66c7337a0
