### ISSUE TITLE
error: target not found: ffmpeg2.8

### ISSUE THREAD

**Issue by tuxarch** [ARCHLabs/Archlabs-Iso#145]
When assembling iso an error:
> error: target not found: ffmpeg2.8
warning: skipping target: sudo
==> ERROR: Failed to install packages to new root

It seems to me in packages.both It is necessary to fix a rigid attachment to a certain version in the package ffmpeg?

**Comment by natemaia** [comment]
It was needed for a short while, `ffmpeg2.8` no longer exists in the official repos.

Changing it to just `ffmpeg` allows the build to work successfully
