### ISSUE TITLE
lsb_release + screenfetch + neofetch

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#15]
now it is archlinux ---> ARCHLabs
[http://archlabs.prophpbb.com/topic91.html](http://archlabs.prophpbb.com/topic91.html)

**Comment by erikdubois** [comment]
confirmed changing the name works

**Comment by osgyan** [comment]
Not only do we need LSB release we also need the ASCII logo. We need to work with Screenfetch package upstream to include ArchLabs as a supported distro, or we need to maintain a patched version of screenfetch in our repo so people can use it from there.

**Comment by erikdubois** [comment]
correct

**Comment by Dobbie03** [comment]
I have attempted a number of times to get the ASCII logo to work with Neofetch to no avail.

Apparently there is a maximum size we need to keep to, I have had no lick in recreating a satisfactory logo in ASCII.

**Comment by erikdubois** [comment]
i would contact screenfetch and explain our case

**Comment by Dobbie03** [comment]
@toola69 I know you approached someone, did you have a reply?

**Comment by osgyan** [comment]
ASCII won't work well with neofetch..We need screenfetch.. fork it and add our changes and try pushing those upstream.. Like other distros have done..

**Comment by Dobbie03** [comment]
I personally prefer Neofetch but if the majority prefers Screenfetch I am happy.

**Comment by erikdubois** [comment]
neofetch is fine by me but also screenfetch should give us a ascii logo
both should work
who contacted who?
I see no issues on both githubs?

**Comment by toola69** [comment]
@erikdubois I contacted the guy from Neofetch but never got a reply

**Comment by ajjames31** [comment]
The neofetch script is generally cleaner and faster. I just got ascii art working for OBR in neofetch, and I'm going to submit a pull request to get it officially supported. If @Dobbie03 will send me the ascii file he's been working on I'll try to get it working and submit a pull request for neofetch for AL as well. You can send it to ajjames31@gmail.com

**Comment by Dobbie03** [comment]
@ajjames31 all done mate, you should have an email now.

**Comment by ajjames31** [comment]
I sent Matt a working config file and ascii for neofetch. I will do pull request to try to get it officially supported.

**Comment by erikdubois** [comment]
great

**Comment by ajjames31** [comment]
I forked neofetch, made the necessary changes to support ARCHlabs, and have sent a pull request to have the changes merged upstream. I will let you guys know when it gets merged. The config and ascii art that I sent to Matt should work for now, however.

**Comment by ajjames31** [comment]
Also, the ID line in /etc/os-release needs to be changed to "ID=archlabs".

**Comment by Dobbie03** [comment]
Excellent, thank you Jody @ajjames31

**Comment by erikdubois** [comment]
done from release 3.4.4

**Comment by erikdubois** [comment]
@Dobbie03 or can it be ARCHLabs instead of archlabs

**Comment by Dobbie03** [comment]
@erikdubois I don't think it is important

**Comment by erikdubois** [comment]
now it is archlabs in 3.4.4
we can always change it later

**Comment by ajjames31** [comment]
It needs to be.lower case on the ID line

**Comment by erikdubois** [comment]
ok done closing

**Comment by erikdubois** [comment]
sorry reopening for the rest of the topic

**Comment by ajjames31** [comment]
Hey guys, the changes have been merged to neofetch and it has been updated. There is now native support for ARCHlabs!

**Comment by Dobbie03** [comment]
That is amazing news.  So happy!!

**Comment by toola69** [comment]
Wow how cool is this

**Comment by erikdubois** [comment]
neofetch is now fixed
new version is in repo

How about screenfetch? any steps taken there ?
@Dobbie03 @toola69 @ajjames31

**Comment by Dobbie03** [comment]
No nothing with screenfetch. We should just stick with Neofetch.

**Comment by erikdubois** [comment]
closing ?

**Comment by Dobbie03** [comment]
Closing this one up.

Not sure if the lsb_release will need to be manually updated or not  Will need to check with next release.

**Comment by erikdubois** [comment]
ok closing
