### ISSUE TITLE
add competition wallpapers

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#18]
[http://archlabs.prophpbb.com/topic62.html](http://archlabs.prophpbb.com/topic62.html)

**Comment by osgyan** [comment]
included a bunch in +3.2. Please reopen issue if that is not what was requested.

**Comment by erikdubois** [comment]
not quite pleased with the wallpapers I saw on [https://github.com/ARCHLabs/archlabs_wallpaper](https://github.com/ARCHLabs/archlabs_wallpaper)

are these competition wallpapers?

**Comment by Dobbie03** [comment]
No, these were contributions from Karl Schneider.

Let me know what you would prefer to see.

**Comment by Dobbie03** [comment]
Also we have had minimal interest in the competition.  I asked Duncan Pringle and Karl Schneider to contribute some work.

**Comment by osgyan** [comment]
added in 3.3
