### ISSUE TITLE
Xfce-slimlock (AUR)

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#2]
needs to be added to the list of applications

[http://archlabs.prophpbb.com/topic65.html](http://archlabs.prophpbb.com/topic65.html)

**Comment by osgyan** [comment]
Saved for +3.3

**Comment by osgyan** [comment]
In 3.3.1 and also in the archlabs_repo now. Please sync and install it now

**Comment by erikdubois** [comment]
close when it is included

**Comment by toola69** [comment]
@erikdubois This has been added to the list. I will close this now

**Comment by erikdubois** [comment]
ok
