### ISSUE TITLE
add Simplescreenrecorder to list of installed applications

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#21]
great tool to add - all my tutorials 600+ are made with it

**Comment by osgyan** [comment]
Will be done in +4 Release

**Comment by Dobbie03** [comment]
I concur.  Please add to the list.

**Comment by osgyan** [comment]
Included in +3.2

**Comment by erikdubois** [comment]
confirmed in archlabs 3.2.1
