### ISSUE TITLE
test if there is full printer support after installation

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#22]
[http://archlabs.prophpbb.com/topic68.html](http://archlabs.prophpbb.com/topic68.html)

**Comment by osgyan** [comment]
Sorry Can't do it myself as I have no printer. If you can help me with the list of packages and config files we need, I can bake that into the next ISO!

**Comment by Dobbie03** [comment]
I have no printer.  Who does?

**Comment by toola69** [comment]
I can do this guys @erikdubois @osgyan

**Comment by erikdubois** [comment]
system-config-printer needs be added to the applications.both file in order to have support
after release of 3.4

**Comment by erikdubois** [comment]
added system-config-printer to packages.both
