### ISSUE TITLE
Numix-circle icon set

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#23]
Suggestion to add numix-circle standard

**Comment by osgyan** [comment]
Will Include in +4

**Comment by Dobbie03** [comment]
Hmm I don't know if I want this included.  With the addition of Papirus we have more themes so far than we need.  I'd prefer to not add Numix Circle in the +4 release.

**Comment by erikdubois** [comment]
up to you.
close it if you decide

**Comment by Dobbie03** [comment]
Yeah I'm going to close this one.
