### ISSUE TITLE
Arc theme 

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#25]
`sudo pacman -S arc-gtk-theme`

Install arc-gtk-theme

**Comment by erikdubois** [comment]
incorporate aur/openbox-arc-git to have a menu consistent with the rest of ARC 
Arc does not support openbox

**Comment by osgyan** [comment]
Will be Included in +4 Iso. Will be released coming weekend

**Comment by Dobbie03** [comment]
I was under the impression we were adapting the Arc theme to suit the AL/BL colours?  Is the default Arc theme preferred?

**Comment by erikdubois** [comment]
let us wait with releasing until we checked all old and new bugs are out of it

**Comment by erikdubois** [comment]
Well the thing with horst3180 aka arc theme is that he is actively developing it. Updates come in - many issues are being dealt with. Let us be honest. Issues I can not begin to understand. So let us use his knowledge and follow all future updates of gtk.
But openbox needs an extra folder - openbox-3 that is not included - we get this folder from AUR but we need to finetune it with the colours we want. 
I have an arc colora script at [https://github.com/erikdubois/Arc-Theme-Colora](https://github.com/erikdubois/Arc-Theme-Colora) I am maintaining anyway that will change the blue colour into any colour we want out of the 16 million.  I have added an example to this github.
Arc-Dark-Tacao has been tweaked to work on archlabs
Select it everywhere (also the border) and the menu will become darker and orange.
[https://github.com/ARCHLabs/archlabs-arc-themes](https://github.com/ARCHLabs/archlabs-arc-themes)

**Comment by Dobbie03** [comment]
Great stuff Erik.  Shall we include the default Arc theme with the intention of having a ArchLabs version come +5?

**Comment by erikdubois** [comment]
Option 1 : 
Included as one of the selections to theme your system (short-term)

Option 2 : 
make it the standard theme when you boot into the system (iso installation)
(mid-term decision)

Option 3 : 
Use bunsenlabs themes - who is going to maintain and do we have this knowledge at all. Is it better looking then Arc?

Theming your distro is a package deal - the theme on its own ... is ok but
the desktop you give the users the first time they look at it should be "dazzling"
They need to become eager to install it further. I know it is superficial ... but that is how you decide.

icons, cursor, conky, theme and wallpaper all matter

I love a dark background and theme.
wallpaper is super (wood with golden logo)
standard conky just needs some colours  (yellow-golden)
cursor ? breeze snow
icons ? paper icons?
theme ? arc theme?

In the end we need to be practical. Ask around who can and will maintain the bunsenlabs themes for the coming years. Is this a priority? Are there other things more important?
Just some things to get you thinking. 
Cheers

**Comment by osgyan** [comment]
Included in +3.2 Build
