### ISSUE TITLE
Script to remove Virtualbox modules

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso#27]
We need a script that resides in the home folder so that after installation the user can easily remove the virtualbox modules

Needs to contain:

sudo pacman -Rns virtualbox-guest-utils virtualbox-guest-modules-arch
sudo rm /etc/modules-load.d/virtualbox.conf

**Comment by osgyan** [comment]
This needs to be done at Calamares Level, The Installer should be able to remove these once installation is done. I need to run through the Calamares source code to put this in

**Comment by Dobbie03** [comment]
I'll change this to a bug in the meantime.

**Comment by Dobbie03** [comment]
@osgyan can this be closed mate?

**Comment by erikdubois** [comment]
still open as
.xinitrc has the line
/usr/bin/VBoxClient-all

which gives us two notifications that virtual box is not running

**Comment by erikdubois** [comment]
i can do this in the cleanup.sh
but this script will always on ssd or on virtualbox
we should included a bash script to figure out if we are on vb

**Comment by Dobbie03** [comment]
Sent using Boxer

On Apr 7, 2017 7:43 AM, Erik Dubois <notifications@github.com> wrote:

i can do this in the cleanup.sh
but this script will always on ssd or on virtualbox
we should included a bash script to figure out if we are on vb

**Comment by erikdubois** [comment]
link to script that we need to include in our cleanup.sh scipt
[link](https://github.com/erikdubois/Archlabs-Nemesis/blob/master/personal/999-only-if-you-are-NOT-on-virtual-box-you-can-run-these-v3.sh)

**Comment by Dobbie03** [comment]
Just tested the script, worked perfectly.  Just has a spelling mistake at the end when the script has run:

"virtual box for guest has been **_remoced_**"

**Comment by erikdubois** [comment]
can this be done automatic with calamares?

**Comment by erikdubois** [comment]
in short term we will solve this with scripts
if an automatic method is found, it will be included
closing for now with consensus of @Dobbie03
