### ISSUE TITLE
Archlabs 3.2.1 : remove quake

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#29]
Remove quake from tint2 and installation

**Comment by toola69** [comment]
Please remove quake @osgyan

**Comment by Dobbie03** [comment]
+ From me on this.

**Comment by erikdubois** [comment]
@Dobbie03 to clear what you mean with this remark

**Comment by Dobbie03** [comment]
Sorry was + 1 from me.

**Comment by osgyan** [comment]
removed.. No problems I can keep using it in my installations but not ship it in iso. 3.3 has no guake.
