### ISSUE TITLE
Archlabs 3.2.1: abif-master

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#30]
secondary installer ? 
Do we need it?
Does it take up much space?
if not install it

**Comment by toola69** [comment]
Please remove this if calamares is working ok @osgyan 
@erikdubois is Calamares opening quicker for you

**Comment by erikdubois** [comment]
no really since i thought it had crashed

**Comment by Dobbie03** [comment]
abif is handy to have for those who have Calamares fail on them.  I'd leave this in.

**Comment by erikdubois** [comment]
I had to use it also in the past.
if maintenance is low and MB are low, I would include it too.

**Comment by Dobbie03** [comment]
@osgyan please include this in the package list for +4.

**Comment by osgyan** [comment]
Currently it is not included. But will include it in next release. I reckon this is a better installer than Calamares.. We are targeting advanced users are we not ??

**Comment by osgyan** [comment]
Keeping open till 3.4

**Comment by Dobbie03** [comment]
@osgyan I'd like to leave ABIF. It's a good back up to Calamares and it's my preferred install option.

**Comment by erikdubois** [comment]
has been added to iso.
I believe it is called AIF
or is this something else

**Comment by erikdubois** [comment]
it is not yet included !!

**Comment by erikdubois** [comment]
continues at @ #76
