### ISSUE TITLE
Archlabs 3.2.1 : obmenu-generator

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#31]
you can install the application obmenu-generator - not much KB
but the OB menu should be the standard from obmenu and no reference to the application obmenu-generator anywhere in the menu.  It was decided at [https://github.com/ARCHLabs/Openbox-Configs/issues/18](https://github.com/ARCHLabs/Openbox-Configs/issues/18)

**Comment by toola69** [comment]
Please remove obmen-generator @osgyan

**Comment by Dobbie03** [comment]
This needs to go.

**Comment by osgyan** [comment]
Removed in 3.3
