### ISSUE TITLE
ArchLabs 3.2.1 : Openbox folder

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#32]
Old version with minecraft still in it. based on obmenu-generator
copy/paste from github
[https://github.com/ARCHLabs/Openbox-Configs](https://github.com/ARCHLabs/Openbox-Configs)
Use this openbox configuration in next release

**Comment by toola69** [comment]
Use openbox configs from Github

**Comment by osgyan** [comment]
That is what was used.in 3.3
