### ISSUE TITLE
ArchLabs 3.2.1 : termite

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#33]
Use termite as standard terminal not xterm. (obmenu-generator)
[https://github.com/ARCHLabs/Openbox-Configs/issues/23](https://github.com/ARCHLabs/Openbox-Configs/issues/23)

**Comment by toola69** [comment]
remove termite and install terminator as in Bunsenlabs.....

**Comment by erikdubois** [comment]
ok will change the menu
@osgyan remove termite and install terminator

**Comment by erikdubois** [comment]
termite pops up in the help section only since we use exo-open now
` termite -T 'man dmenu' -e man dmenu`
not sure if terminator is accepting the same line of code
investigation required

**Comment by Dobbie03** [comment]
I found that the only terminal that work which commands from obmenu is URXVT.

**Comment by erikdubois** [comment]
fine tell @osgyan what he needs to do

**Comment by Dobbie03** [comment]
@osgyan please leave Termite and URXVT as the treminals.

@erikdubois the menu is good as it is other than the exo entries

**Comment by osgyan** [comment]
both are in.  However we need to think about this becasue BL has terminator. I also perfer Terminator, this is just a suggestion. Terminte is OK too. Please re-open with a request to add Terminator.
