### ISSUE TITLE
Archlabs 3.2.1 : mailclient

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#34]
noticed in the preferred applications that we do not have a mail client
geary, thunderbird, evolution, ...

**Comment by toola69** [comment]
install thunderbird

**Comment by Dobbie03** [comment]
I don't think this is needed.  Most OB users in my experience seem to either use Mutt or check email online.

Including Thunderbird just adds extra to the ISO that isn't really required.  If the user really wants a email client then they will install one.

**Comment by osgyan** [comment]
OB users are generally advanced users.. all we need to ship is a out of the box working system and they can add more software themselves.. I have a vision of ARCHLABS as a platform with Minimum application choices made by us and let users decide what they want.. We are targeting advanced linux users
