### ISSUE TITLE
Archlabs 3.2.1 : browser - W3M text browser

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#36]
do we need or want this one?

**Comment by toola69** [comment]
we need w3m to show the image in neofetch or we use screenfetch with our own ascii logo.
Ascii logo needs to be designed....

**Comment by erikdubois** [comment]
i do not know if this is the same
i found it in the obmenu-generated menu ...

**Comment by Dobbie03** [comment]
I don't think this is required.  User can install if need be.

**Comment by osgyan** [comment]
user can add it if needed.. Closing
