### ISSUE TITLE
Archlabs 3.2.1 : gimp missing

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#37]

**Comment by toola69** [comment]
install gimp and add to menu

**Comment by erikdubois** [comment]
gimp in menu 
now we need to add it to the application list @osgyan

**Comment by osgyan** [comment]
Included in 3.3.. Please eaise a bug with Instructions for adding the Gimp Splash and I will include in 3.4 Next Week.
