### ISSUE TITLE
Archlabs 3.2.1 : Thunar and Pcmanfm

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#38]
Do we need both?
Thunar would be my choice. Fast and extendible with scripts

**Comment by toola69** [comment]
remove pcmanfm

**Comment by erikdubois** [comment]
pcmanfm not in menu
@osgyan can you remove pcmanfm from application list

**Comment by Dobbie03** [comment]
Thunar please.  I have on my system PCmanFM installed as a back up but I very rarely use it.

**Comment by osgyan** [comment]
PacmanFM is still there will remove it in 3.4. 3.3 focussed more on fixing Openbox itself

**Comment by erikdubois** [comment]
is gone in 3.3.4
