### ISSUE TITLE
Archlabs 3.2.1 : leafpad

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#39]
Did we have leafpad in previous releases?
Wondering. Geany was/is standard.

**Comment by toola69** [comment]
remove leafpad and remove from menu

**Comment by erikdubois** [comment]
ok 
assign menu stuff to me

**Comment by erikdubois** [comment]
not in our menu - must have been in obmenu-generator
delete it from application list?

**Comment by toola69** [comment]
@erikdubois Yes mate

**Comment by erikdubois** [comment]
@osgyan please delete leafpad from application list

**Comment by Dobbie03** [comment]
Geany is our preferred editor.

**Comment by osgyan** [comment]
Too Late.. Leafpad is still there.. Please save it for 3.4

**Comment by erikdubois** [comment]
mirage and leafpad of the application list closing
