### ISSUE TITLE
Archlabs 3.2.1 : lock screen

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#41]
new lockscreen - some kind of black fiber?
Is that ok?

**Comment by toola69** [comment]
This definitely needs a new theme...

**Comment by erikdubois** [comment]
i believe the theme was the wallpaper with golden logo which was fine by me

**Comment by toola69** [comment]
@osgyan Go ahead with this mate. No wallpaper change

**Comment by Dobbie03** [comment]
Closing.

**Comment by erikdubois** [comment]
only lock issues if solved
@osgyan will need to change this - but since he starts from scratch from an earlier version this might be in order already
@osgyan it is up to you to close this one

**Comment by Dobbie03** [comment]
By the way this is what the lockscreen should look like

![archlabs](https://cloud.githubusercontent.com/assets/14961904/24574462/69d11bce-16ef-11e7-81f8-707266c34526.png)

**Comment by erikdubois** [comment]
thanks @Dobbie03 a picture clears things up

**Comment by Dobbie03** [comment]
I think this can be closed as it isn't really a bug and all questions have been answered.

**Comment by erikdubois** [comment]
But will @osgyan include it into his iso?

**Comment by osgyan** [comment]
Slimlock theme is in now in 3.3 closing
