### ISSUE TITLE
Archlabs 3.2.1 : Openbox Menu's - Display Keybinds - pipemenu's al-kb-pipemenu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#42]
Since ~/.config/openbox is not based on github of [https://github.com/ARCHLabs/Openbox-Configs](https://github.com/ARCHLabs/Openbox-Configs) I have deleted the openbox folder of Archlabs 3.2.1 and copy/pasted.

**Comment by erikdubois** [comment]
all other pipemenu's
compton 
help
conky
printer
...

**Comment by toola69** [comment]
Please use openbox configs from github

**Comment by osgyan** [comment]
Used all configs from Github.. Please confirm and re-open the bug if issue exists
