### ISSUE TITLE
Archlabs 3.2.1 : gnumeric

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#50]
install application or exclude from menu

**Comment by toola69** [comment]
need a script for the menu

**Comment by erikdubois** [comment]
why do you need a script??

**Comment by toola69** [comment]
@erikdubois I was thinking we dont install Libreoffice and just give them gnumeric to get started. I was thinking of scripts to install software like Bunsen has but no we will do this way instead. 
@osgyan Please install this

**Comment by erikdubois** [comment]
I never ever use libreoffice and stay in geany or sublime-text but the average user is not writing scripts...
I would install it too.
assigning it to @osgyan

**Comment by Dobbie03** [comment]
Let's do away with LibreOffice and run with gnumeric and geany.  Any other suggestions?  Obmenu will need to be updated to suit.

**Comment by Dobbie03** [comment]
Also helps us deliver a smaller ISO.

**Comment by erikdubois** [comment]
I would like to keep libreoffice even though I never use it. I know it takes place. I have never seen a distro without some kind of Office tool.

**Comment by Dobbie03** [comment]
What if we can deliver the same with alternatives.  I very rarely use LO myself.  I'm going to boot up a live ISO of BL to see what they have on offer.

**Comment by erikdubois** [comment]
bunsenlabs
provides libreoffice writer
and the rest needs to be installed with scripts

**Comment by erikdubois** [comment]
personnally I do not like these installation scripts
we have had them in the past and we abandoned them

**Comment by Dobbie03** [comment]
I agree, if we could provide a welcome script a lot of the extra packages we want could be installed after install.

**Comment by erikdubois** [comment]
that is not what i am saying

**Comment by erikdubois** [comment]
then you need obmenu-generator
your menu is **static**
people would install stuff that will never show up

**Comment by erikdubois** [comment]
we do not have to make things more complex then they are
leave libreoffice in for now and we will see later

**Comment by osgyan** [comment]
We have both now in 3.3  Make a choice please for 3.4
