### ISSUE TITLE
Archlabs 3.2.1 : opening something with sudo takes very long

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#52]
gparted  (root)
file manager as root
texteditor as root

they all take longer then previous versions imo
to be confirmed

**Comment by toola69** [comment]
cant simulate on my version..

**Comment by toola69** [comment]
Matt can you please look at this. Is it doing the same on your version

**Comment by toola69** [comment]
@Dobbie03 I cant simulate this on my version mate.

**Comment by Dobbie03** [comment]
@toola69 @erikdubois I am having this issue too.  Ran "gksu thunar" from terminal, no outputs and approx 1 minute later a root thunar opened up.

After a reboot a root thunar opens instantly.

**Comment by erikdubois** [comment]
aha did not reboot

**Comment by Dobbie03** [comment]
Can we close this one?

**Comment by erikdubois** [comment]
let us leave it and test it on the next release

**Comment by osgyan** [comment]
Still Testing this will update

**Comment by erikdubois** [comment]
This seems to be solved in 3.3.
TO BE CONFIRMED!

**Comment by erikdubois** [comment]
closing this one we can always reopen
