### ISSUE TITLE
Archlabs 3.2.1: gmrun delete in menu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#54]
can we get rid of the menu gmrun
edit config file does not work
delete category help
delete man page

**Comment by toola69** [comment]
go ahead

**Comment by toola69** [comment]
Erik could you please go through the menu and make sure its up to date with the changes from the list we have here....

**Comment by erikdubois** [comment]
okidoki
the menu is mine

**Comment by erikdubois** [comment]
committed
