### ISSUE TITLE
Archlabs 3.2.1 : Preferences Display

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/archlabs-iso#55]
keep Arandr
delete Help? category
delete Man xrandr

change menu?

**Comment by toola69** [comment]
Yes go ahead

**Comment by toola69** [comment]
Go ahead with this

**Comment by osgyan** [comment]
Keeping Track for th Iso.. Please only Comment. I will close upon including in Iso.

**Comment by erikdubois** [comment]
ok i will assign myself to this task.

**Comment by erikdubois** [comment]
updated - closing
