### ISSUE TITLE
Still have CSD in Pamac

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/archlabs-iso#56]
As the title indicates I still have CSD enabled in Pamac, screenshot link attached.

![screenshot_2017-04-01_18-17-31](https://cloud.githubusercontent.com/assets/14961904/24575622/d5313ce2-1707-11e7-9b4c-9b8d36d03d7a.png)

**Comment by erikdubois** [comment]
You lost me here?

**Comment by Dobbie03** [comment]
Take a look at the screenshot, we still have client side decorations enabled as well as a title bar.  We wanted CSD disabled in place of titlebar controls.

**Comment by erikdubois** [comment]
I believe I heard Rajat talk about that.
I will assign it to him.

**Comment by osgyan** [comment]
This will stay However we also have our window borders, It looks a bit odd, However it is not completely out of place. The best we can integrate the GTK apps so far. I am open to suggestions if any for improving this further. Please open an issue with suggestions to do it better. We will take care of it then
