### ISSUE TITLE
Proposal - Replace Mirage with Gpicview

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso#57]
This is based purely on aesthetic reasons.  Mirage is actually ugly as sin, Gpicview has a nicer look to it

Mirage:

![mirage](https://cloud.githubusercontent.com/assets/14961904/24585125/dd5f7f76-17d6-11e7-914a-ba3bfb131c70.png)

Gpicview:

![gpicviewer](https://cloud.githubusercontent.com/assets/14961904/24585127/e51a44d0-17d6-11e7-8265-ca512305ea7a.png)

Adds a nicer look to Dsitro.

@erikdubois @osgyan @toola69

**Comment by erikdubois** [comment]
anything is better then mirage
go

**Comment by Dobbie03** [comment]
@osgyan , please replace Mirage with Gpicview

**Comment by erikdubois** [comment]
`			<menu id="screenshot" label="Screenshooter">
				<item label="Screenshot in 5">
					<action name="Execute">
						<command>scrot -d 5 'ARCHLabs.png' -e  'mv $f ~/Pictures/ ; mirage ~/Pictures/$f'</command>
					</action>
				</item>
				<item label="Screenshot in 10">
					<action name="Execute">
						<command>scrot -d 10 'ARCHLabs.png' -e  'mv $f ~/Pictures/ ; mirage ~/Pictures/$f'</command>
					</action>
				</item>
				<item label="Screenshot With Selection">
					<action name="Execute">
						<execute>scrot -s 'ARCHLabs-Selection.png' -e 'mv $f ~/Pictures/ ; mirage ~/Pictures/$f'</execute>
					</action>
				</item>
			</menu>
		</menu>`

**Comment by Dobbie03** [comment]
I have tested already on my system, hence my proposal.  I will adjust the menu.xml to suit.

**Comment by Dobbie03** [comment]
Changes have been made, feel free to test.

**Comment by erikdubois** [comment]
has been committed
