### ISSUE TITLE
Gmrun taking over alt+f2

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/archlabs-iso#58]
Gmrun is taking over rc.xml keybinds which wants to call Drun.

Solution, remove all keyboard shortcuts from XFCE4-keyboard-settings

**Comment by erikdubois** [comment]
alt + F2 is app finder of xfce here
an idea ?

**Comment by osgyan** [comment]
Removed XFCE-Settings-Editor and XFCE-Appearance.. want to keep xfce shit out of this... gmrun is enabled in 3.3 Could be changed to drun if people don't like it..
