### ISSUE TITLE
Updated openbox tint2 and conky folder from github in skel

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#61]
we have now a folder **scripts** to copy files from local github and put them in the correct folder
.config/openbox
.config/tint2
.config/conky

I have added now a script to build an iso automatically as well

more to come

information for RAJ

**Comment by osgyan** [comment]
Did you make changes to archlabs-iso or individual folders on Github for OpenBox Configurations ?

**Comment by erikdubois** [comment]
Oh yes i made changes - like we told over the phone 3/4/2017
