### ISSUE TITLE
users will get wallpapers in their personal Pictures folder

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#62]
archlabs-iso/archiso/airootfs/etc/skel/Pictures/
Personally I would not appreciate this.
The wallpapers are in /usr/share/background 
Proposal: delete from iso

**Comment by Dobbie03** [comment]
I don't like wallpapers from any distribution being in my personal pictures folder either.

Best idea is to move them to the /usr/share/backgrounds folder.

**Comment by erikdubois** [comment]
ok done

**Comment by erikdubois** [comment]
moved them to /usr/share/background
