### ISSUE TITLE
Archlabs 3.3.3 : ALOB folder on archiso

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#64]
The application Alob will save date to folder ~/.config/blob.

I think ALOB is old remnants and can be deleted
Archlabs-Iso/archiso/airootfs/etc/skel/.config/ALOB/

**Comment by Dobbie03** [comment]
I had originally converted all the folders/configs/scripts from BL to AL.  This maybe one I missed.

**Comment by erikdubois** [comment]
not clear if i can delete it

**Comment by Dobbie03** [comment]
Best idea will be to rename it ~/.config/alob.

**Comment by erikdubois** [comment]
try it out on the 3.3.4
as i think alob will not be used 
it will make a blob??

**Comment by Dobbie03** [comment]
Will check it out.

**Comment by erikdubois** [comment]
in the mean did a lot of testing with this obmenu bug
imo you can delete it
i guess someone created this folder to have a backup of settings (just in case)
alob makes a directory blob
first time you run it it creates this folder blob and does a backup
second time you run it
nothing happens
if you rename blob to anything else
it runs again

Pretty sure I can delete it

**Comment by Dobbie03** [comment]
Just delete it mate.

**Comment by osgyan** [comment]
It is there in archlabs/abif in case you need it again. We can remove it from the build for now.
