### ISSUE TITLE
Request to add to repo's - breeze snow cursor

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#68]
0 aur/breeze-snow-cursor-theme 1.0-3 (15)
    Breeze Snow cursor theme.

Can we add this one to the installation?
Can you explain how to do this task?
Film it?

**Comment by toola69** [comment]
Erik you just add the cursor theme to icons and pick them using lxappearance

**Comment by osgyan** [comment]
Compile it from AUR, Dump the created package into archlabs_repo (You should have git cloned that to your disk) update db (updaterepo.sh file to be exeucted) git push and add breeze-snow-cursor-theme to packages.both, Rebuild Image and it will be there.
