### ISSUE TITLE
Archlabs 3.3.4 : preferred applications

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#69]
in obmenu you can choose terminal
a popup comes up
![chooseprefferredapplication](https://cloud.githubusercontent.com/assets/10594806/24617504/6231c8ae-1894-11e7-8f37-ae13ecb3ea19.png)

You can only choose 
rxvt unicode
x terminal
and we have so many more terminals.

How to get the rest in the dropdown? Would be nice.

**Comment by Dobbie03** [comment]
Doesn't it give you an option to type the terminal you want?

**Comment by erikdubois** [comment]
yes you can type
but how can the user know what we installed 
there are 6 of them 
remember my screenshot with all the terminal that i pimped to look like the arc theme

**Comment by erikdubois** [comment]
added file for termite to airootfs/etc/skel/.local/share/xfce4/helpers/
let us test if this works

**Comment by erikdubois** [comment]
above code did not help
what if we launched we launced exo-prefferred applications only once after reboot
is it posssible to put this in the iso? @osgyan

**Comment by osgyan** [comment]
Please do  not add stuff out of BL. We are trying to bring BL experience to Arch Labs,, We need to have only what is there in BL, and the user can install stuff from AUR/ pacman.. Don't think tooo much..

**Comment by osgyan** [comment]
Just choose from BL, create a config file and ship that..

**Comment by erikdubois** [comment]
i want to keep looking when i have the time 
if not... simple exo-open out and termite and thunar in

**Comment by erikdubois** [comment]
closing this
the user chooses what he wants
extra menu Preferred applications as well
