### ISSUE TITLE
Menu link for File Manager

### ISSUE THREAD

**Issue by toola69** [ARCHLabs/Archlabs-Iso#71]
@osgyan @erikdubois 
When clicking on File manager in the terminal it asks for preferred application
Can we make it open Thunar

**Comment by erikdubois** [comment]
yes we can
/home/erik/.config/xfce4/helpers.rc
done

FileManager=thunar
TerminalEmulator=termite
WebBrowser=chromium

ARE THESE CHOICES OK THEN CLOSE.

**Comment by toola69** [comment]
Erik can we please change TerminalEmulator to terminator

**Comment by Dobbie03** [comment]
Go ahead please Erik.

**Comment by erikdubois** [comment]
ok committed
