### ISSUE TITLE
3.4 We need AUR pacakges compiled and added to repo

### ISSUE THREAD

**Issue by osgyan** [ARCHLabs/Archlabs-Iso#73]
Yes we do need to compile the packages from AUR and add them to repo, Update the repo and sync changes to git. This is because mkarchiso does not support AUR. So we compile AUR pacakges and either put them in a local repo or put them into archlabs_repo. Let me know if this is not clear.

**Comment by erikdubois** [comment]
clear but do put them online.
by the way I have changed the names on archlabs github
can we change your repo archlabs-repo to Archlabs-Repo 
and
archlabs-keyring to Archlabs-Keyring

I did not dare change it. No repercussions?

**Comment by osgyan** [comment]
Removed archlabs-repo.. We will use archlabs_repo

**Comment by erikdubois** [comment]
ok closing
