### ISSUE TITLE
Pamac has twin decoration bars

### ISSUE THREAD

**Issue by toola69** [ARCHLabs/Archlabs-Iso#74]
@osgyan pamac has two sets of buttons on top of each other mate.

**Comment by erikdubois** [comment]
![pamacupdater](https://cloud.githubusercontent.com/assets/10594806/24644928/4d02b45c-1916-11e7-9a08-acefd26b31a1.png)

**Comment by osgyan** [comment]
This is ought to happen, We will have two bars without csd, At least the outer bar is the same as all other applications, We should not either use noCSD or use alternative non GTK applications. simple as that..

**Comment by erikdubois** [comment]
what can we to solve it?

**Comment by Dobbie03** [comment]
Is there a GTK2 version of Pamac or a similar styled update/package manager?

**Comment by toola69** [comment]
@Dobbie03 There is a terminal based one called pacli.
Its great mate I use it everyday

**Comment by erikdubois** [comment]
i have used pacli as well previously to fix things (red lines)

**Comment by Dobbie03** [comment]
What about a GUI option for those that prefer that option?

**Comment by erikdubois** [comment]
if you delete the following installed package in packages.both this is solved
gtk3-nocsd-git

**Comment by toola69** [comment]
Install pacli and in the menu add Pacli and execute termite -e pacli
That will bring it straight up in a Shell for you

**Comment by Dobbie03** [comment]
@erikdubois, this removes the double decorations?

**Comment by erikdubois** [comment]
i am going to delete these packages from the list 

#fix gtk themes
gtk3-nocsd-git
lib32-libgtk3-nocsd-git

Delete these from your system and immediately solves pamac double title bars.
Will use it for a few weeks without these two files.
hashtagging them out for now
