### ISSUE TITLE
abif

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#76]
[http://archlabs.prophpbb.com/topic47.html](http://archlabs.prophpbb.com/topic47.html)

add in the folder mentioned on forum
sudo /abif-master/abif

**Comment by erikdubois** [comment]
strange though
script is called aif
where should I get the code from 
url?

**Comment by Dobbie03** [comment]
That I cannot answer, @ajjames31 can you help here?

**Comment by osgyan** [comment]
check our github, I put it at ARCHLABS/abif
