### ISSUE TITLE
Remove abif-master after installation

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#77]
add to cleanup script to delete folder /abif-master on root

**Comment by erikdubois** [comment]
waiting for input of Jody  @ajjames31

**Comment by erikdubois** [comment]
i think this one is succesful
confirm and close

**Comment by erikdubois** [comment]
confirmed 
deleting works

**Comment by Dobbie03** [comment]
Could this clean up script be included somewhere in the next build?

**Comment by erikdubois** [comment]
it is included but it does not work
have tried two hours ago with help of Jody
not nearer to a solution

**Comment by erikdubois** [comment]
abif-master is cleaned after installation
