### ISSUE TITLE
Ob-menu crashes

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#78]
Two solution 

Manual 
edit .xinitrc
delete exec openbox-session there
edit .xsession
add exec openbox-session here
REBOOT

Automatic via aur package
(re-edit - not sure anymore if this works)
solution 1 DOES work - stick to that

install xinit-xsession 
it will make sure .xinitrc is started as a session
.xinitrc has the start code inside
exec openbox-session
.xsession has no excec code for openbox...

Both have been tested and both work.

Implement at a future iso - to be tested on new iso

**Comment by erikdubois** [comment]
ok we will see in the future if we can make the scripts work...
deciding to delete it in the menu for now
keeping it in the applications.both
I hope Jody can fix this one in next release

**Comment by osgyan** [comment]
xinit-xsession seems more feasible. Let met try that in the new build and see how that goes.

**Comment by erikdubois** [comment]
please check it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by erikdubois** [comment]
checking this now

**Comment by erikdubois** [comment]
in version 3.4.1 this is all good
