### ISSUE TITLE
thunar configure custom actions

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#79]
We should gather all our 
**custom actions**
of thunar and include the best of them
my current list is now

- open terminal here
- set wallpaper single (same wallpaper on dual screen)
- set wallpaper dual  (dualscreen wallpaper)
- search with catfish
- extract here 
- compare (meld)
- run (scripts)

**Comment by Dobbie03** [comment]
I'd like to see these included.

**Comment by erikdubois** [comment]
me too I am using them all the time
(not the wallpapers)

**Comment by osgyan** [comment]
I think all of this should be in AUR,I can compile them and put them in the repo.

**Comment by Dobbie03** [comment]
Good idea Rajat

**Comment by erikdubois** [comment]
it is easier to put the custom actions in the skel
no maintaining needed
we have enough work as is

**Comment by erikdubois** [comment]
here are mine
[link](https://github.com/erikdubois/Archlabs-Nemesis/blob/master/personal/settings/thunar/uca.xml)
share your document please - pastebin or so

**Comment by erikdubois** [comment]
mine have been added to 3.4.1

**Comment by Dobbie03** [comment]
That will mike life a little easier :)

**Comment by erikdubois** [comment]
we should gather more 
and improve mine

**Comment by erikdubois** [comment]
@ARCHLabs/core-members can you guys check your systems
what custom actions do you like to see included?

**Comment by Dobbie03** [comment]
All I think we need is a open thunar as root, edit as root and open terminal here.

**Comment by erikdubois** [comment]
keeping all as is and closing
