### ISSUE TITLE
linux or linux-lts kernel

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#80]
was it your choice to use 4.10 kernel rather than the newest
people of arch expect to see the latest kernel. 
include the newest in future releases?

**Comment by Dobbie03** [comment]
This was a suggestion of @toola69.

My personal preference is the latest kernel.  Failing that, can we add an option to choose either one?

**Comment by erikdubois** [comment]
let us figure this one out after release 3.4

**Comment by osgyan** [comment]
Can't include it like this, We need to customize our build.sh and mkarchiso to ensure that we add support for Linux-lts. I can take a look at this and update

**Comment by erikdubois** [comment]
updating to linux-lts was piece of cake
experienced arch user will have no problem with that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by toola69** [comment]
@erikdubois @osgyan I'd just leave it as the default kernel

**Comment by erikdubois** [comment]
ok best thing to do is keep it as it is now
updating the kernel is not that difficult
closing
