### ISSUE TITLE
3.4.0- Browse Here shortcut still pointing to PcManFM

### ISSUE THREAD

**Issue by osgyan** [ARCHLabs/Archlabs-Iso#82]
![3 4-bug-1](https://cloud.githubusercontent.com/assets/15225405/24815764/04cba1fe-1bf4-11e7-81c6-b51e9ba568aa.png)

**Comment by osgyan** [comment]
Change the Line Number 27 from open_folder_cmd=pcmanfm  to open_folder_cmd=thunar  in 
 /usr/bin/al-places-pipemenu  and this error will go. 

whosoever does the next build can do this.

**Comment by osgyan** [comment]
Solution is tested to work fine. Assigning to myself for next build.

**Comment by erikdubois** [comment]
great 
i skipped that one in the testing

**Comment by Dobbie03** [comment]
Pipemenu corrected with Thunar rather than PCmanFM.

**Comment by Dobbie03** [comment]
Tested and works perfectly.

**Comment by erikdubois** [comment]
checked and closed
