### ISSUE TITLE
3.4.0 -Screen Tearing with Compton

### ISSUE THREAD

**Issue by osgyan** [ARCHLabs/Archlabs-Iso#83]
Not sure what changed but I am getting screen tearing with Nouveau Driver. Is this expected?

**Comment by osgyan** [comment]
Fix is to enable backend= glx in place of backend=xrenderer in compton.conf  Will need to be taken care of in Next release

**Comment by erikdubois** [comment]
there were issues with glx so i changed back to xrender
this might be user and hardware dependent
follow this up and let users know if that is the case

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by erikdubois** [comment]
do other have issues wit screentearing
i have nvidia over here

**Comment by toola69** [comment]
@erikdubois I did have mate but after putting glx into my compton.conf it is fixed plus tweaking my xorg.conf

**Comment by erikdubois** [comment]
where can we communicate this information the best?

**Comment by erikdubois** [comment]
idea is it feasable to make an extra menu in the pipemenu to source a script that changes glx and xrender with a sed command...?

**Comment by toola69** [comment]
That's a good idea

**Comment by ajjames31** [comment]
There is also a graphical application called paranoid that allows for making this change as well as setting other Compton configurations. I can provide a PKGBUILD for it if you'd like to include it. Its at https://github.com/obrevenge/obr-packages/paranoid

**Comment by erikdubois** [comment]
@ajjames31 can you accept my google hangout invitation
i want to ask you some questions ...

**Comment by erikdubois** [comment]
no screen sharing reported after 3.4.6
let us agree to reopen if it starts again
backend xrender in this release
