### ISSUE TITLE
3.4.0 - Exit screen is different than BL

### ISSUE THREAD

**Issue by osgyan** [ARCHLabs/Archlabs-Iso#84]
![2017-04-08--1491616578_1920x1080_scrot](https://cloud.githubusercontent.com/assets/15225405/24818584/c7fc9782-1bfe-11e7-89da-969d6961f521.png)

**Comment by osgyan** [comment]
Looks like sardi look, I changed once to Sardi icons in themes but then changed back to Faenza and it still is unchanged, either way this is not what we should have. We should have the exact one like BL..

**Comment by Dobbie03** [comment]
This is the one compromise we are making with the dedicated BL look.  None of us like AL-Exit, and it was awkward.  To top it off, it appears BL are returning to the old styled #! exit anyway.

**Comment by osgyan** [comment]
Ok Then If this is agreed, then I am fine with this. I will close .. Please remove /usr/bin/al-exit script as that is broken. I thought we have this look because al-exit is broken.. lol..
