### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Iso#87]
Is this required:
http://archlabs.prophpbb.com/topic125.html

**Comment by erikdubois** [comment]
no we discovered this as wall but it seems we dit not make a issue here on github
next release we will have this line deleted in xsession
#/bin/zsh --login -i ~/.xinitrc
this causes openbox-session to run twice so the logout has trouble logging you out...

**Comment by erikdubois** [comment]
related to this one - there was a issue report on another github
[https://github.com/ARCHLabs/Archlabs-Openbox-Configs/issues/60](https://github.com/ARCHLabs/Archlabs-Openbox-Configs/issues/60)
