### ISSUE TITLE
What if we supported printer support

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#90]
it only takes these applications to do it
sudo pacman -S cups cups-pdf ghostscript gsfonts libcups hplip system-config-printer --noconfirm --needed
systemctl enable org.cups.cupsd.service
systemctl start org.cups.cupsd.service

**Comment by Dobbie03** [comment]
I'm all for printer support.

**Comment by erikdubois** [comment]
in they go then

**Comment by erikdubois** [comment]
done for version 3.4.6
