### ISSUE TITLE
geany - dark theme

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#92]
i do not like the white geany background so I immediately change to the dark version.
Should we include a dark theme?
Should we set it as default?

**Comment by toola69** [comment]
@erikdubois Include a dark theme mate

**Comment by Dobbie03** [comment]
Include and set as default.

**Comment by erikdubois** [comment]
ok will do

**Comment by erikdubois** [comment]
added to github other files 
done
