### ISSUE TITLE
ctrl + alt + backspace

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#94]
I like to have the option to be able to stop xorg

Terminating Xorg with Ctrl+Alt+Backspace

By default, the key combination Ctrl+Alt+Backspace is disabled. You can enable it by passing terminate:ctrl_alt_bksp to XkbOptions. This can also be done by binding a key to Terminate_Server in xmodmap (which undoes any existing XkbOptions setting). In order for either method to work, one also needs to have DontZap set to "off" in ServerFlags; however, from at least version R6.8.0 (year 2004) [1] this is the default. 
[link](https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg)
or here in the code
[link](https://github.com/SwagArch/swagarch-build/blob/master/airootfs/etc/X11/xorg.conf.d/99-killX.conf)

**Comment by erikdubois** [comment]
@Dobbie03 what do you think
add it ?

**Comment by Dobbie03** [comment]
Yes,  I agree, add it.

**Comment by erikdubois** [comment]
added in v3.5.6

**Comment by erikdubois** [comment]
deleted again from v3.5.8
causes many problems in virtualbox and ssd
compton crashes
no wallpaper etc ...
