### ISSUE TITLE
Do we need three browsers?

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#95]
[formum link](http://archlabs.prophpbb.com/post560.html#p560)
What do you think about deleting opera?
Is any of us using this?
I use firefox all the time...
in the future i believe vivaldi is going to be a popular browser -- try it  -- superfast

**Comment by toola69** [comment]
@erikdubois Delete it mate. 3 Browsers is insane

**Comment by Dobbie03** [comment]
Kill Opera, I only use Waterfox myself anyway.

**Comment by erikdubois** [comment]
will kill it

**Comment by erikdubois** [comment]
gone
