### ISSUE TITLE
addding standard folders

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#96]
how to we add standard folders to the users home folder like music, video etc...

**Comment by Dobbie03** [comment]
I'm not sure what you mean, aren't they already there?

**Comment by erikdubois** [comment]
ah yes sorry
i mean the folder in the left column of thunar
the bookmarks

**Comment by Dobbie03** [comment]
You click drag it to the sidebar

**Comment by erikdubois** [comment]
can we add them automatically for the users.
if we can then i would like to add .config and .config/openbox as well

**Comment by Dobbie03** [comment]
We can add them, how we do that for shipping I don't know.

**Comment by erikdubois** [comment]
in respect to release 4.0 - closing this for now
