### ISSUE TITLE
audacious sets mime links on wrong extensions...

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#97]
audacious gives us already two bugs... that i have discovered - they are all linked to mime

bug 1 : firefox - download something go to download folder in menu and in stead of thunar we get audacious - solved via forum search - added mimeapp.list a line to open thunar
bug 2 : peek - maked animated gifs - you get a popup to open the folder were the gif is - that link will not open thunar. That is also linked to audacious and what else...

there are alternatives to play music right? clementine for one, ... etc...

**Comment by Dobbie03** [comment]
I'm not getting this on any of my installs.

**Comment by erikdubois** [comment]
take firefox
download something from the net
then go to the top
you see an arrow
click on the arrow
do not click on the file/download but on the folder behind it to open the folder
that USED to open audacious - fixed in 3.6.0
now i discover a new bug....

**Comment by Dobbie03** [comment]
With this issue seeming impossible to cure, let's put the vote to remove Audacious and swap out with Deadbeef.
@erikdubois @osgyan @toola69 

Let us know either yay or nay.

It's a yay from me.

**Comment by erikdubois** [comment]
this was a non-issue - genuine installation of 3.6.0 was working fine.
mime changes must be changed after installing additional software.

**Comment by erikdubois** [comment]
reopening
did 3.6.1 installation. added lastpass and xmarks and synchronisation of extenions
 and had again a link from folder to audacious
![2017-04-23--1492975916_3840x1080_scrot](https://cloud.githubusercontent.com/assets/10594806/25316706/8cb16e26-286c-11e7-844f-e1bc4f873cf1.png)

**Comment by erikdubois** [comment]
i did a uninstallation of audacity and audacity-plugins.
The first one also has a line upon uninstalling
Updating the desktop fiile MIME type cache
i believe that is were the trouble is after reading many articles on the net.

**Would advise to replace audacity with deadbeef. Is awesome alternative.**

**Comment by toola69** [comment]
Deadbeef is cool

**Comment by erikdubois** [comment]
can be delete audacious completely  and replace any and all with deadbeef
shortcuts ... @Dobbie03

**Comment by erikdubois** [comment]
audacious has been removed in favour of deadbeef
