### ISSUE TITLE
Cooverglobus

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Iso#98]
add it to the iso
[forum](http://archlabs.prophpbb.com/topic140.html)

**Comment by toola69** [comment]
@erikdubois @Dobbie03 I've never been able to get this to work.
Is there anyway we can make a conky that shows song info and coverart

**Comment by erikdubois** [comment]
we will try to implement it for 4.0 else later

**Comment by Dobbie03** [comment]
@toola69 I have a couple of custom configs, depends on what music player you're using.

**Comment by Dobbie03** [comment]
Closing this as we aren't adding.  User can install from the AUR Archive
